const {test, expect, chromium, } = require('@playwright/test')

test('Amazon',async({})=>{
    test.setTimeout(120000)
    const browser =  await chromium.launch()
    const context = await browser.newContext()

    const page= await context.newPage()

    await page.goto('https://www.amazon.in/')
    await page.hover("#nav-link-accountList-nav-line-1")
    await page.waitForSelector("(//span[@class='nav-action-inner'])[1]")
    await page.click("(//span[@class='nav-action-inner'])[1]")
    await page.locator("#ap_email_login").fill("9952104627")
    await page.click("//input[@type='submit']")
    await page.waitForSelector('#ap_password')
    await page.locator("#ap_password").fill('ajay9952')
    await page.click("#signInSubmit")
    await page.waitForSelector('#twotabsearchtextbox')
    await page.locator('#twotabsearchtextbox').fill('sound bar')
    await page.click('#nav-search-submit-button')
    await page.waitForSelector("//span[normalize-space()='boAt Aavante Bar 610 Bluetooth Soundbar with 25W RMS Signature Sound, 2.0 Channel with Dual Passive Radiators, Upto 7 Hours Playback & Multi Connectivity(Charcoal Black)']")
    await page.waitForTimeout(1000)
    const pagePromise =context.waitForEvent('page')
    await page.click("//span[normalize-space()='boAt Aavante Bar 610 Bluetooth Soundbar with 25W RMS Signature Sound, 2.0 Channel with Dual Passive Radiators, Upto 7 Hours Playback & Multi Connectivity(Charcoal Black)']")
    const newPage = await pagePromise
    await newPage.waitForSelector("(//i[@class='a-icon a-icon-popover'])[1]")
    await newPage.click("(//i[@class='a-icon a-icon-popover'])[1]")
    await newPage.waitForSelector("#native_dropdown_selected_style_name")
    await newPage.locator('#native_dropdown_selected_style_name').selectText(' 120W(Alexa) ')
    await newPage.click('#add-to-cart-button')
    await newPage.waitForSelector("//span[contains(text(),'Proceed to checkout')]")
    await newPage.click("//span[contains(text(),'Proceed to checkout')]")
    await newPage.waitForSelector("//span[@id='shipToThisAddressButton']")
    await newPage.click("//span[@id='shipToThisAddressButton']")
    await newPage.waitForSelector("address-ui-widgets-form-submit-button")
    await newPage.click("address-ui-widgets-form-submit-button")

})