const { test, expect } = require ('@playwright/test')
const { fileURLToPath } = require('url')

test('SauceDemo', async ({page})=>{
    await page.goto("https://www.saucedemo.com/")
    await page.locator("#user-name").fill("standard_user")
    await page.locator("#password").fill('secret_sauce')
    await page.click('#login-button')

    await page.click("//div[contains(text(),'Sauce Labs Fleece Jacket')]")
    await page.click("#add-to-cart")
    await page.click('#back-to-products')
    await page.click("//div[contains(text(),'Sauce Labs Backpack')]")
    await page.click('#add-to-cart')
    await page.click('.shopping_cart_link')
    await page.click('#checkout')
    await page.locator('#first-name').fill('Sunny')
    await page.locator('#last-name').fill('Leone')
    await page.locator('#postal-code').fill('627401')
    await page.click('#continue')
    await page.click('#finish')
    await page.click('#back-to-products')
    await page.click("//button[@id='react-burger-menu-btn']")
    await page.click("//a[@id='logout_sidebar_link']")
})